### ISSUE TITLE
NeXAs - Python script importing bytefile

### ISSUE THREAD

**Issue by marcussacana** [regomne/chinesize#1]
The bytefile not is a valid module to import here....
i try with, Python 2.7.9, 3.2 and 3.4

you can send-me py of this module?

**Comment by regomne** [comment]
I've added the bytefile with py2.x and py3.x to chinesize/Others.

**Comment by marcussacana** [comment]
very Thanks Man \o/
Very very Thanks
i'am brazilian :V: not speak english kkkk thanks man

**Comment by marcussacana** [comment]
i find now...
https://github.com/regomne/chinesize/Others
don't exist.... you can see please?

**Comment by regomne** [comment]
here:
https://github.com/regomne/chinesize/tree/master/Others

**Comment by marcussacana** [comment]
ohh, thanksssssssssssssssssssssssss
hauahuahuahuahu
thanks man...
