### ISSUE TITLE
Question: how can we get the opcode from the ybn script?

### ISSUE THREAD

**Issue by 0xh3LL0** [regomne/chinesize#12]
when i try to extract the script, it gave me "cant guess the op code"

**Comment by regomne** [comment]
The opcodes differs in each version of Yu-ris engine. If you can't analyze it yourself, I don't have idea, either.
In other way, you can try to give a ybn which has the text, for example: yst00XXX.ybn where XXX is the maximum number in all the file names.
If it can't guess, upload the ybn to me and I will improve the algorithm of guessing. 
If it works, I will add opcode output option and you can use the opcode for other ybns in this game.

**Comment by 0xh3LL0** [comment]
here is it... 
[ysbin.zip](https://github.com/regomne/chinesize/files/2079216/ysbin.zip)

**Comment by regomne** [comment]
fixed. recompile and read the usage, please.

**Comment by 0xh3LL0** [comment]
thank you very much!
