### ISSUE TITLE
Latest extybn update crash the game

### ISSUE THREAD

**Issue by 0xh3LL0** [regomne/chinesize#13]
at first, it was look like this, the text is cutted, but i wont bother to create an issue since i thought it was my game problem
![exybn2](https://user-images.githubusercontent.com/23132217/41265015-e8b2ec44-6da4-11e8-8ff5-9580112836ab.png)
but then this [commit](https://github.com/regomne/chinesize/commit/c39bf446c438480932589eda959ea949d97e88ea) fix this issue
![exybn4](https://user-images.githubusercontent.com/23132217/41265033-fb4a78cc-6da4-11e8-97b8-44bb0c2b3102.png)
and the latest [commit](https://github.com/regomne/chinesize/commit/605bc6b6fbe1347c8a1807ccc998f3aa1ddf9fc5) crash the game, it say something about yst00087.ybn, but i didnt even touch that file, since i'm working with yst00108.ybn
![exybn5](https://user-images.githubusercontent.com/23132217/41265054-10f3ecd0-6da5-11e8-9066-c11a5fa0f162.png)

actually it doesnt matter since i can use the earlier version, but i just want to let you know it

**Comment by regomne** [comment]
When the error dialog displays? after that text?

**Comment by regomne** [comment]
Emm, the latest commit has no business with extYbn. It only affects the ExtYpf.py, and that is only a tool for testing. DO NOT use it to extract files from ypf.
You can use [GARBro](https://github.com/morkt/GARbro) to extract and pack ypf files.

**Comment by 0xh3LL0** [comment]
huh? looks like you're right...
guess i link them wrong, i have 3 extybn here, and the working one are the second extybn
and yes, i use garbro to pack them...
