### ISSUE TITLE
这里的 ExHIBIT 的 rld 的 key 文件是用什么生成的。生成其 key 的文件或工具应该怎么用？

### ISSUE THREAD

**Issue by a65090482** [regomne/chinesize#14]
如题所示。

**Comment by regomne** [comment]
这个key是从exe文件中提取的，我的提取方法是使用调试器分析，没有工具提取……

**Comment by a65090482** [comment]
> 这个key是从exe文件中提取的，我的提取方法是使用调试器分析，没有工具提取……

嗯，可以帮解决我一件事吗？我用Python运行一人开发解密脚本遇到错误了；请教一下；那人往往没空管这些事。
链接：https://pan.baidu.com/s/1qBtteLpu3jesYKcyup1v-g

**Comment by HathawayLinNoa** [comment]
大佬 想问下怎么提取KEY..  是ExHIBIT引擎的作品

**Comment by regomne** [comment]
> 大佬 想问下怎么提取KEY.. 是ExHIBIT引擎的作品

我只会通过手动分析exe来提取，需要有一定的逆向能力
