### ISSUE TITLE
使用go build生成的cst.exe无法导出txt

### ISSUE THREAD

**Issue by Shinya-Shimokawa** [regomne/chinesize#15]
一直都有这样的提示，但没看到转换。
![捕获](https://user-images.githubusercontent.com/45751534/55292811-a1664980-5421-11e9-86f3-6b749c15b244.PNG)

**Comment by regomne** [comment]
To extract:
`cst -e -cst <cstname> -o <txtname> [-cp CP]`
To pack:
`cst -p -cst <cstname> -txt <txtname> -o <output_cst> [-cp CP]`

**Comment by Shinya-Shimokawa** [comment]
但是直接Insert以后Shift_JIS以外的字符不兼容该令何解，如何兼容简中/繁中汉字和带调号的拼音呢？
![捕获1](https://user-images.githubusercontent.com/45751534/55309618-f3928380-5490-11e9-9eae-0be2e52f13c6.PNG)
![捕获](https://user-images.githubusercontent.com/45751534/55309623-f7260a80-5490-11e9-9bef-b525794b9631.PNG)
