### ISSUE TITLE
将译稿txt导入以后无法获得完整显示的问题

### ISSUE THREAD

**Issue by Shinya-Shimokawa** [regomne/chinesize#16]
直接Insert以后Shift_JIS以外的字符不兼容该令何解，如何兼容简中/繁中汉字和带调号的拼音呢？
![捕获1](https://user-images.githubusercontent.com/45751534/55309618-f3928380-5490-11e9-9eae-0be2e52f13c6.PNG)
![捕获](https://user-images.githubusercontent.com/45751534/55309623-f7260a80-5490-11e9-9bef-b525794b9631.PNG)

_Originally posted by @Shinya-Shimokawa in https://github.com/regomne/chinesize/issues/15#issuecomment-478463660_

**Comment by regomne** [comment]
显示中文的话应该使用936编码来导入，同时需要修改exe使其内部使用中文字符集的字体。具体方法请搜索各种教程。

**Comment by Shinya-Shimokawa** [comment]
> 显示中文的话应该使用936编码来导入，同时需要修改exe使其内部使用中文字符集的字体。具体方法请搜索各种教程。

调了一下，还是有问题。

主程序：
CreateFontIndirectA断点+内存断点确定80位置改成了86。
![80改86](https://user-images.githubusercontent.com/45751534/55417339-1c0aa280-55a3-11e9-8317-23902ba271b5.PNG)

cst：
932导出，936导入。
![9](https://user-images.githubusercontent.com/45751534/55417710-cd113d00-55a3-11e9-819d-00adcc889e1e.PNG)

结果为日文：乱码，中文：箭头，英文：I wanna cry
![捕获](https://user-images.githubusercontent.com/45751534/55418108-896b0300-55a4-11e9-9027-779734a6f868.PNG)
![效果](https://user-images.githubusercontent.com/45751534/55418115-8e2fb700-55a4-11e9-983f-e367f1db7aa1.PNG)

**Comment by regomne** [comment]
1 命令行程序usage中，[]是optional的意思。请先参阅一些命令行程序的用法，或者阅读一下源代码再使用。
2 exe有可能还需要进行字符边界检查的处理。

**Comment by Shinya-Shimokawa** [comment]
> 1 命令行程序usage中，[]是optional的意思。请先参阅一些命令行程序的用法，或者阅读一下源代码再使用。
> 2 exe有可能还需要进行字符边界检查的处理。

改了一下：
```
cst -e -cst OP01.cst -o OP01.txt
cst -p -cst OP01.cst -txt OP01.txt -o OP01.cst -cp 936
```
目前的显示：
![2](https://user-images.githubusercontent.com/45751534/55487701-31de9d00-5661-11e9-84e0-2a9ca88d0221.PNG)
![3](https://user-images.githubusercontent.com/45751534/55487714-36a35100-5661-11e9-8520-e15e037e70b0.PNG)

然后照此例：

> 00406765  |.  8A06          mov     al, byte ptr [esi]
> 00406767  |.  3C 80         cmp     al, 80
> 00406769  |.  76 04         jbe     short 0040676F
> 0040676B  |.  3C A0         cmp     al, 0A0
> 0040676D  |.  72 08         jb      short 00406777
> 0040676F  |>  3C E0         cmp     al, 0E0
> 00406771  |.  72 5D         jb      short 004067D0
> 00406773  |.  3C FC         cmp     al, 0FC
> 00406775  |.  77 59         ja      short 004067D0


查找得cmp al,80有3处，A0没有，E0和FC只有一处，其他地方也跟例子不一样。
![1](https://user-images.githubusercontent.com/45751534/55488489-c5649d80-5662-11e9-8e80-6524ad06b607.PNG)
![4](https://user-images.githubusercontent.com/45751534/55488501-cc8bab80-5662-11e9-9363-9e50d3ee555e.PNG)
![5](https://user-images.githubusercontent.com/45751534/55488512-d01f3280-5662-11e9-85a1-ac668be9076a.PNG)
将FC处以FE替换过，没有效果。

**Comment by regomne** [comment]
直截了当地说，需要把第一张图中的cmp al,9f改为fe，同时把下面的cmp al,7e改为fe。另外两张不要改。
但是看起来你完全不明白这个改动的原理，所以建议你学习一下字符集、windows对字符的显示原理等知识，更进一步的需要学习汇编语言、程序调试等知识。如果这些都不懂的话，你依然无法自己解决其他问题。

这里是提issue的地方，不是提question的地方。

**Comment by Shinya-Shimokawa** [comment]
> 直截了当地说，需要把第一张图中的cmp al,9f改为fe，同时把下面的cmp al,7e改为fe。另外两张不要改。
> 但是看起来你完全不明白这个改动的原理，所以建议你学习一下字符集、windows对字符的显示原理等知识，更进一步的需要学习汇编语言、程序调试等知识。如果这些都不懂的话，你依然无法自己解决其他问题。
> 
> 这里是提issue的地方，不是提question的地方。

明白了，看来这并不是照葫芦画瓢就能解决的事。总之非常感谢能对一个纯外行指导至此。
