### ISSUE TITLE
CIRCUS图片处理问题

### ISSUE THREAD

**Issue by MZSHproject** [regomne/chinesize#17]
2016年后CIRCUS更新了引擎，新版的CIRCUS引擎的CRX图片貌似稍微更新了一下，不过还能用GARbro提取出来，但是用大佬你的DCPC图片编码处理回去后图片能够读取，但是整个图片就完全模糊了。
是不是和位深有关？新版的CRX的位深是24位，用DCPC图片编码后的位深是32位。另外是否和zlib压缩的级别有关？

**Comment by regomne** [comment]
不好意思那个图片编码的程序不是我写的，我也不清楚原委，不过既然garbro可以提取，那解码算法就是已知的，尝试写一个编码算法试试？

**Comment by MZSHproject** [comment]
> 不好意思那个图片编码的程序不是我写的，我也不清楚原委，不过既然garbro可以提取，那解码算法就是已知的，尝试写一个编码算法试试？

OK，我试着自己写一下吧。
