### ISSUE TITLE
what's "strfile" in your py code ?

### ISSUE THREAD

**Issue by ultrapre** [regomne/chinesize#18]
in your few py files I find `import strfile`, however I couldn't find any module or any files named strfile ?

sample: `Xuse/extIndex.py`

**Comment by ultrapre** [comment]
I found one closed same issue, but I hope I can get strfile's source code.

**Comment by regomne** [comment]
Sorry I've lost it, too. But it's so simple that you can rewrite it by a similar file: bytefile.py.
