### ISSUE TITLE
关于ACPX的toml文件

### ISSUE THREAD

**Issue by MZSHproject** [regomne/chinesize#19]
在extListBin.py里面似乎需要一个关于*.bin的toml文件，这玩意儿似乎需要自己写。
不过没怎么看明白要写些什么东西，可以说一下toml里面要记录些什么吗？

**Comment by regomne** [comment]
这个我忘了传，明天我传一下

**Comment by MZSHproject** [comment]
> 这个我忘了传，明天我传一下

好的，有劳了。
