### ISSUE TITLE
NeXAs - Script Repack to bin bug

### ISSUE THREAD

**Issue by marcussacana** [regomne/chinesize#2]
i test this tool now, and the text has extracted (Thanks for this)
but to repack the script output is equal to original...
I try view the py file and change .replace('._bin','.txt') to .replace('.bin', '.txt')
The script now is edited but Corrupted... view the printscreen...
![Print](https://cloud.githubusercontent.com/assets/10576957/5812260/94f4f3ea-a04d-11e4-8e98-a2c120eec8e8.png)

Yours Source:

for f in os.listdir(path1):
    fs=open(path1+f,'rb')
    stm=bytefile.ByteIO(fs.read())
    if os.path.exists(path2+f.replace('._bin','.txt')):
        fs=open(path2+f.replace('._bin','.txt'),'rb')
        lines=fs.read().decode('U16').encode('936','replace').split(b'\r\n')
        stm=packTxt(stm,lines)
    fs=open(path3+f.replace('._bin','.bin'),'wb')
    fs.write(stm[0:])

I Edited to:

for f in os.listdir(path1):
    fs=open(path1+f,'rb')
    stm=bytefile.ByteIO(fs.read())
    if os.path.exists(path2+f.replace('.bin','.txt')):
        fs=open(path2+f.replace('.bin','.txt'),'rb')
        lines=fs.read().decode('U16').encode('936','replace').split(b'\r\n')
        stm=packTxt(stm,lines)
    fs=open(path3+f.replace('.bin','.bin'),'wb')
    fs.write(stm[0:])

**Comment by marcussacana** [comment]
original script
![print](https://cloud.githubusercontent.com/assets/10576957/5812285/07562c9c-a04e-11e4-9d30-7afe893c65db.png)

The Original file of the game
http://www12.zippyshare.com/v/fkeYpar3/file.html

**Comment by regomne** [comment]
you may try to comment the packTxtBin:18:
#stm.seek(4)

**Comment by regomne** [comment]
sorry, this code:

def packTxt(stm,lines):
    #stm.seek(4)
    inst_count=stm.readu32()
    stm.seek(inst_count*8+4)
    count=stm.readu32()
    pos1=stm.tell()

**Comment by marcussacana** [comment]
thanks man, thanks for help \o

**Comment by marcussacana** [comment]
wow, works now thanksss
full code now...

#py3.2

import zlib
import bytefile
import os

path1=r'Script\\'
path2=r'txt\\'
path3=r'NewScript\\'

def packTxtBlock(lines):
    block=bytearray()
    for l in lines:
        block+=l+b'\x00'
    return block

def packTxt(stm,lines):
    #stm.seek(4)
    inst_count=stm.readu32()
    stm.seek(inst_count*8+4)
    count=stm.readu32()
    pos1=stm.tell()
    for i in range(count):
        stm.readstr()
    pos2=stm.tell()
    newstm=bytearray()
    newstm+=stm[0:pos1]
    newstm+=packTxtBlock(lines)
    newstm+=stm[pos2:]
    return newstm

for f in os.listdir(path1):
    fs=open(path1+f,'rb')
    stm=bytefile.ByteIO(fs.read())
    if os.path.exists(path2+f.replace('.bin','.txt')):
        fs=open(path2+f.replace('.bin','.txt'),'rb')
        lines=fs.read().decode('U16').encode('936','replace').split(b'\r\n')
        stm=packTxt(stm,lines)
    fs=open(path3+f.replace('._bin','.bin'),'wb')
    fs.write(stm[0:])
