### ISSUE TITLE
Yu-ris, euphoria, problem in extracting and packing ybn

### ISSUE THREAD

**Issue by dmc31a42** [regomne/chinesize#21]
# Hello
Before asking, Thank you for making great tools.

# Problems
I have problems extracting and packing ybn file in euphoria.
In 'yurisybn3.0.py', result of YSTB() and CODE2YSTB() is different to original ybn file(file size is larger than original. Exactly, number of code count, codeData, ArgData, OffList is same, ResData is different)
In 'extYbn.go', program exit at guessYbnOp() because 'Can't guess the opcode'. 

# Reason
Why I try to do is,
euphoria english version seems to use image font. Related code is in data\script\eris\es_font.yst (yst00011.ybn). First, in this code, 'cgsys/font/font18/' folder is mentioned and in that folder, font image actually exist. Other, es_font.yst look differ to original es_font.yst file in yu-ris engine distribution package, and in this code there are many charactors are listed and patterend.
So, I assume if I can change es_font.yst then, I can print other charactor not included as default.
In addition, texts are also in yst, so I will modify text detail whether able to extract and repack. (In same length, I can change)

# Environment
* Game: euphoria HD remaster english version
* engine: Yu-ris 0.474
* OS: Windows 10
* Run script in VS Code, python 2.7, golang lastest
* I use extYbn.go only as decrypt ybn because explain above.
* I use yurisybn3.0.py as extract .code and .txt file and try to repack them to .ybn
* XOR key is different, please tell me how to send xor key and ybn files to you, or just upload here

# Common Caution about both yurisybn3.0.py and extYbn.go
## Decryption for size is not multiple of 4.
ref: d1c6139cce91f0ff56caafde2f24c4d211a0c495
If decryption is end where offset address is not multiple of 4 each code, argument, ressource, offlist block

yst0008.ybn header
```
59 53 54 42 DA 01 00 00 3F 02 00 00 FC 08 00 00 
A4 31 00 00 EA 22 00 00 FC 08 00 00 00 00 00 00
```
So contents should be
Section	|Address					|Size(Hex)|Size
-----------|--------------------------------|-----------|-------
Code	|0x00000020 ~ 0x0000091B	|8FC		|2300
Args		|0x0000091C ~ 0x00003ABF	|31A4	|12708
Res		|0x00003AC0 ~ 0x00005DA9	|22EA	|8938
OffList	|0x00005DAA ~ 0x000066A5	|8FC		|2300

Size of res is not multiple of 4. so decrypt ends after second XOR operation.
Then, decrypt start from first XOR operation in offlist.
I checked using ollydbg reverse engineering debugger.

So, I change extYbn.go code 
from
https://github.com/regomne/chinesize/blob/4211cae59a850f495745a9fd0db1c03fcb780d4c/yuris/extYbn/extYbn.go#L78-L85
https://github.com/regomne/chinesize/blob/4211cae59a850f495745a9fd0db1c03fcb780d4c/yuris/extYbn/extYbn.go#L87-L154
https://github.com/regomne/chinesize/blob/4211cae59a850f495745a9fd0db1c03fcb780d4c/yuris/extYbn/extYbn.go#L262-L268
to
```go
func decryptYbn(stm []byte, key []byte, start uint32, length uint32) {
	if len(key) != 4 {
		panic("key length error")
	}
	for i := start; i < start+length; i++ {
		stm[i] ^= key[(i-start)&3]
	}
}
```
```go
func parseYbn(oriStm []byte, key []byte) (script ybnInfo, err error) {
	stm := bytes.NewReader(oriStm)
	binary.Read(stm, binary.LittleEndian, &script.Header)
	logln("header:", script.Header)
	header := &script.Header
	if bytes.Compare(header.Magic[:], []byte("YSTB")) != 0 ||
		header.CodeSize != header.InstCnt*4 {
		err = fmt.Errorf("not a ybn file or file format error")
		return
	}
	fileSize, _ := stm.Seek(0, 2)
	if uint32(binary.Size(header))+header.CodeSize+header.ArgSize+header.ResourceSize+
		header.OffSize != uint32(fileSize) {
		err = fmt.Errorf("file size error")
		return
	}
	if header.Resv != 0 {
		fmt.Println("reserved is not 0, maybe can't extract all the info")
	}
	var decryptedStm io.ReadSeeker
	if bytes.Compare(key, []byte("\x00\x00\x00\x00")) != 0 {
		logf("decrypting, key is:%02x %02x %02x %02x\n", key[0], key[1], key[2], key[3])
		decryptYbn(oriStm, key, uint32(binary.Size(header)), header.CodeSize)
		decryptYbn(oriStm, key, uint32(binary.Size(header))+header.CodeSize, header.ArgSize)
		decryptYbn(oriStm, key, uint32(binary.Size(header))+header.CodeSize+header.ArgSize, header.ResourceSize)
		decryptYbn(oriStm, key, uint32(binary.Size(header))+header.CodeSize+header.ArgSize+header.ResourceSize, header.OffSize)
		decryptedStm = bytes.NewReader(oriStm)
	} else {
		decryptedStm = bytes.NewReader(oriStm)
	}

	logln("write decrypted file...")
	s := []string{*inYbnName, ".decrypt"}
	err1 := ioutil.WriteFile(strings.Join(s, ""), oriStm, 0644)
	fmt.Println(err1)

	logln("reading sections...")
	decryptedStm.Seek(int64(binary.Size(header)), 0)
	script.Insts = make([]instInfo, header.InstCnt)
	rawInsts := make([]YInst, header.InstCnt)
	binary.Read(decryptedStm, binary.LittleEndian, &rawInsts)
	var tArg YArg
	rargs := make([]YArg, header.ArgSize/uint32(binary.Size(tArg)))
	binary.Read(decryptedStm, binary.LittleEndian, &rargs)
	resStartOff, _ := decryptedStm.Seek(0, 1)
	rargIdx := 0
	logln("parsing instructions...")
	for i, rinst := range rawInsts {
		inst := &script.Insts[i]
		inst.Op = rinst.Op
		inst.Unk = rinst.Unk
		inst.Args = make([]argInfo, rinst.ArgCnt)
		for j := 0; j < int(rinst.ArgCnt); j++ {
			rarg := &rargs[rargIdx]
			rargIdx++
			if rargIdx > len(rargs) {
				err = fmt.Errorf("count of arguments exceed limit")
				return
			}
			inst.Args[j].Type = rarg.Type
			inst.Args[j].Value = rarg.Value
			if rarg.Type == 0 && rinst.ArgCnt != 1 {
				inst.Args[j].ResInfo = rarg.ResSize
				inst.Args[j].ResOffset = rarg.ResOffset
			} else {
				decryptedStm.Seek(resStartOff+int64(rarg.ResOffset), 0)
				res := &inst.Args[j].Res
				if rarg.Type == 3 {
					var resInfo YResInfo
					binary.Read(decryptedStm, binary.LittleEndian, &resInfo)
					res.Type = resInfo.Type
					res.Res = make([]byte, resInfo.Len)
					decryptedStm.Read(res.Res)
				} else {
					res.ResRaw = make([]byte, rarg.ResSize)
					decryptedStm.Read(res.ResRaw)
				}
			}
		}
	}
	offTblOffset := uint32(binary.Size(header)) + header.CodeSize + header.ArgSize + header.ResourceSize
	decryptedStm.Seek(int64(offTblOffset), 0)
	script.Offs = make([]uint32, header.InstCnt)
	binary.Read(decryptedStm, binary.LittleEndian, &script.Offs)
	return
}
```
```go
	// if bytes.Compare(key, []byte("\x00\x00\x00\x00")) != 0 {
	// 	logf("decrypting, key is:%02x %02x %02x %02x\n", key[0], key[1], key[2], key[3])
	// 	decryptYbn(oriStm, key)
	// }
	logln("parsing ybn...")
	script, err := parseYbn(oriStm, key)
```

# Caution about yurisybn3.0.py In this case
## Caution 1:  dummy size of YSTL is different as code
In euphoria, dummy size of YSTL is 20byte. So, I changed
https://github.com/regomne/chinesize/blob/4211cae59a850f495745a9fd0db1c03fcb780d4c/yuris/yurisybn3.0.py#L83
to 
```python
		dummy=YBN.read(20)
```
## Caution 2: args(?), or res(?) contain '<', '>', ':' charactor so replace from text file fail.
ref: 6e868b724c12a8e6f2a8bcdb5d638828908f8e2d
Result of YSTB() contain '<', '>' and ':' charactors in args or res code.
Variable sample and regexp 
So, I change full logic 
from
https://github.com/regomne/chinesize/blob/4211cae59a850f495745a9fd0db1c03fcb780d4c/yuris/yurisybn3.0.py#L217-L224
to
```python
import re
```
```python
				LQuote=0
				while True:
					LQuote=Res.find('<',LQuote)
					doubleQueta = Res.find('"', LQuote)
					RQuote=Res.find('>',LQuote)
					if LQuote==-1: break
					if (doubleQueta==-1 or RQuote<doubleQueta) and RQuote!=-1:
						Res=Res[:LQuote]+TXT[int(Res[LQuote+1:RQuote])]+Res[RQuote+1:]
					LQuote+=1
				ResLen=0
				ResStr=[]
				for Res1 in re.findall("(?:[^ ]*?:)(?:\"(?: |[^\"])*?\"|.*?)(?:,|$)", Res):
					if Res1[-1]==',':
						Res1 = Res1[0:-1]
					ResType, Str = [n.strip() for n in re.split(':', Res1, 1)]
```

# Summary
## I want to extract yst script file from ybn and modify and repack them to ybn

# Thank you for reading long issue.

**Comment by regomne** [comment]
Thank you for improving the code!

**Comment by dmc31a42** [comment]
Oh, hm. There is unsolved problem.
.ybn(A) file->decode->.code and .txt file -> pack -> .ybn(B).
In this situation, A and B is different. How can I solve it?

**Comment by regomne** [comment]
I'm sorry but `yurisybn3.0.py` is not written by me, and I have never maintained it before.
But extYbn is written by me, and it supports to export all code to a json. Maybe you can add supports to import back from the json?

**Comment by dmc31a42** [comment]
Actually, I cannot export it by using extYbn.go because 'Can't guess the opcode' error.
So, I issued to get your help

**Comment by regomne** [comment]
I thought this problem had been solved after the decryption issue fixed.
Please upload a ybn file which contains texts, and I will try to fix it in free time.

**Comment by dmc31a42** [comment]
Thanks, I'll upload in 12 hours

**Comment by dmc31a42** [comment]
# key
```
0x30731B78
```
```go
[]byte("\x78\x1B\x73\x30")
```

# data\script\eris\es_font.yst
font related script
* encrypted: yst00011.ybn
* decrypted: ys00011.decrypt.ybn (made using my patch version d1c6139cce91f0ff56caafde2f24c4d211a0c495 )

# data\script\userscript\01-op\01-ＯＰ・主人公目を覚ます.txt
senario and text script
* encrypted: yst00140.ybn
* decrypted: yst00140.decrypted (made using my patch version d1c6139cce91f0ff56caafde2f24c4d211a0c495 )

# using extYbn.go, result is: ( using f6b9b24a4c816db11b66b8456aa529c58292d31f  my patch version)
![image](https://user-images.githubusercontent.com/13437953/79780343-bab49d80-8376-11ea-8dfa-7705a35a0be3.png)

# expecting
can execute guessYbnOp() function and get json and text file.


[ysbin.zip](https://github.com/regomne/chinesize/files/4504937/ysbin.zip)

**Comment by regomne** [comment]
Thank you for providing the files. I think I've realized why guessOps is not working.

It uses the first byte of the character in the SJIS/GBK (which is 0x80 < x < 0xff) as a standard to determine whether a string is a message or a control string, while english strings are not in that range.

It may take some time to find a way to guess whether an ASCII string is a control string or an english message.

**Comment by kazurabakouta** [comment]
I get memory error while running extYbn.go 
How do I fix this?

**Comment by regomne** [comment]
I will fix this error soon.

**Comment by mrlewie** [comment]
> I will fix this error soon.

Hi have you fixed this memory issue ? I am trying to decode a yu-ris v48 ybn and extYbn.go crashes due to memory issues

**Comment by regomne** [comment]
> > I will fix this error soon.
> 
> Hi have you fixed this memory issue ? I am trying to decode a yu-ris v48 ybn and extYbn.go crashes due to memory issues

This may causes by a wrong key. See `About the key` section in help texts.

**Comment by regomne** [comment]
@dmc31a42 Sorry for long long pauses. Now extYbn supports some english ybns.
