### ISSUE TITLE
eden* Steam version

### ISSUE THREAD

**Issue by Mantas-B** [regomne/chinesize#24]
VN: eden*
Link: https://store.steampowered.com/app/315810/eden/
Engine: Musica (minori)
File extension: .paz

Hello! I had been wanting to retranslate this visual novel to my native language for a while now. Could your tools help with unpacking and repacking files? From what I've gathered so far, fuckpaz (from Inori/FuckGalEngine) and GARbro can decode earlier versions of eden*, but not the Steam version as it has different keys. I've asked here https://github.com/Inori/FuckGalEngine/issues/37 and received instructions, but haven't been successful so far. Recently someone else https://github.com/Inori/FuckGalEngine/issues/47 had successfully discovered 2 of 3 needed parts, so dat_key is remaining. Could you possibly help with that or know anyone else who could or already has done it? I have zero programming knowledge so any help or pointers are very appreciated.

**Comment by regomne** [comment]
The decryption key of Musica engine may be required only by analyzing the exe. Sorry but I have no idea about other methods.
