### ISSUE TITLE
AdvPlayer pnautil improvements

### ISSUE THREAD

**Issue by baconwaifu** [regomne/chinesize#26]
I've figured out most of the missing fields in the PNA per-frame structure. all fields except base X and Y are u32, base coordinates are i32.
* padding? (all examples I've seen are zeros)
* Frame index (can be stored out of order; all tested files make more sense when sorted by this)
* base X coordinate (where the image is placed on the 'canvas')
* base Y NOTE: these CAN BE NEGATIVE. (I've only seen this *once*, but it's possible)
* frame width
* frame height
* 3 u32s of stuff that I don't know
* length.

**Comment by regomne** [comment]
Thank you! I've updated the code.
