### ISSUE TITLE
关于favorite的hook MyProcessString2内obj的寻址问题

### ISSUE THREAD

**Issue by AyamiKaze** [regomne/chinesize#27]
大大好，我最近在研究favorite的汉化技术，看到大大写的hook代码感觉还是挺有帮助的。
不过就像问下ScriptObject* obj = (ScriptObject*)(regs->ebx + 0xf1b58);里面0xf1b58的地址是怎么来的。
顺便再问问exthcb里面parser.ParseTxt的exBlocks里面四个函数地址是怎么找到，谢谢。

**Comment by regomne** [comment]
第一个问题是靠分析exe，需要有相关基础技能才能做；第二个问题，你需要先设置extOriginalScript开关，执行py解析整个hcb脚本，然后阅读这个脚本，找到其中包含需要翻译的文本的函数，然后填写到里面，并关闭extOriginalScript再次执行。
