### ISSUE TITLE
Error when trying to get op code

### ISSUE THREAD

**Issue by 0xh3LL0** [regomne/chinesize#28]
![error](https://user-images.githubusercontent.com/23132217/113469509-46d0af80-9478-11eb-8114-6af63ea0f0c5.png)

here is the sample file
[ysbin.zip](https://github.com/regomne/chinesize/files/6252001/ysbin.zip)

**Comment by regomne** [comment]
Extybn needs a key to decrypt ybn files before parsing it. You may try to debug the game executable to get the key.
