### ISSUE TITLE
Problem starting extYbn.go

### ISSUE THREAD

**Issue by Cetaindark** [regomne/chinesize#29]
Hello, when I try to run extYbn.go, I get these message:

![Problem](https://user-images.githubusercontent.com/83465874/116721844-0bc18d80-a9de-11eb-9755-807d61c6a348.PNG)

I´m completly unfamiliar with go-prgramms, so could you please tell me what I have to do to etrakt text from my Ybn-files?

Thanks in advance and sorry for the dumb question

**Comment by regomne** [comment]
Fixed. Now it can build with `go build`.
