### ISSUE TITLE
NeXAs - Fail to repack to *.pac - Only Report

### ISSUE THREAD

**Issue by marcussacana** [regomne/chinesize#3]
![temp](https://cloud.githubusercontent.com/assets/10576957/5812542/2bafa4c8-a054-11e4-9936-dd83960ec4ba.png)

and i try use the ~Giga_pac_Assage.exe~
but...
![temp](https://cloud.githubusercontent.com/assets/10576957/5812548/7523d87c-a054-11e4-8f64-b5cad745b9f9.png)

and i try rebuild the ~Giga_pac_Assage.exe~
but...
![image](https://cloud.githubusercontent.com/assets/10576957/5812588/134d59ba-a055-11e4-9683-79b1c7ced5ee.png)

here not exist the zlib.h (i have here), but i not have the my.h

this is only report, i use the arc_conv to repack \o
Very Very Thanks for support man, really!

**Comment by regomne** [comment]
thanks, but Giga_pac_Assage is not my code. and I have not used it before.
