### ISSUE TITLE
help decript file

### ISSUE THREAD

**Issue by Azsesa** [regomne/chinesize#30]
Kimi ni Semaru Otome no Lesson
https://drive.google.com/file/d/1naPt3GPiygy0lLqquui1zDMlLj7aEhR5/view?usp=sharing

**Comment by regomne** [comment]
Follow the steps:

1. Guess the op code:
  `extybn.exe -e -ybn yst00114.ybn -output-opcode`

2. Use the opcode to extract texts (replace the file names yourself):
  `extybn.exe -e -ybn ystXXXXX.ybn -op-msg 91 -op-call 29 -txt ystXXXXX.txt`
