### ISSUE TITLE
I don't know what to do, only some of the scripts are exported

### ISSUE THREAD

**Issue by Renneta** [regomne/chinesize#31]
When I try to export ybn scripts from 00000 it gives me "cant guess the opcode", but trying to export 0018X, I got the desired result. Please help, I'm not good at programming at all...

**Comment by regomne** [comment]
Please upload the files, and I'll take a look.

**Comment by Renneta** [comment]
Here
[ysbin.zip](https://github.com/regomne/chinesize/files/6730500/ysbin.zip)

**Comment by regomne** [comment]
Follow the steps:

1. Guess the op code:
  `extybn.exe -e -ybn yst00181.ybn -output-opcode`

2. Use the opcode to extract texts (replace the file names yourself):
  `extybn.exe -e -ybn ystXXXXX.ybn -op-msg 90 -op-call 29 -txt ystXXXXX.txt`

**Comment by Renneta** [comment]
I tried but the txt is empty...

**Comment by Renneta** [comment]
[yst00001.txt](https://github.com/regomne/chinesize/files/6730575/yst00001.txt)

**Comment by CodeSpoof** [comment]
Some script files only contain instructions and no strings. The instuctions are commonly not relevant for translation.
