### ISSUE TITLE
How to use the tool to extract and repack .hg3 images

### ISSUE THREAD

**Issue by tbhoang12** [regomne/chinesize#35]
Hi when I using your tool ,click on the ext.exe to open it nothing happened ,I also tried to drag sys_title.hg3 from my game file into the exe but nothing come out 
Can you make a wiki guide on how to use it and also the command example ?
https://disk.yandex.ru/d/LBurawmVm5KvHg

**Comment by regomne** [comment]
Please run it in Command Line or Powershell. It will prints the help without argumnets:
```
D:\temp\exthg3>ext
Usage of ext:
  -e    extract hg3
  -i string
        hg3 file name(with -e) or png image folder(with -p)
  -o string
        output name
  -p    pack hg3
```
