### ISSUE TITLE
About rUGP tools

### ISSUE THREAD

**Issue by MishaIac** [regomne/chinesize#36]
Hi. I would like to know if the tools are relevant for rugp 6.2? (Schwarzesmarken (https://vndb.org/v14910))
If so, how do I use them? As I see it, the tools are for python 2, not python 3.
In fact, the translation of Schwarzesmarken has been ready since 2019, but the translation has never been able to be built into the game.

**Comment by regomne** [comment]
Usually, each version of rUGP has many differences, so I think the tools can't work for it. Reading the code and modifying it by self may help you let it work.

**Comment by MishaIac** [comment]
There are no problems with pasting text into rUGP, but there are problems with images. There is not a single normal tool for editing graphics in rUGP. I have already analyzed the code myself a little, and found out that graphics problems can arise only if the edited image is larger than the original. If the edited image is smaller than the original, then there should be no problems. Only now I am not a programmer, and I cannot write a tool for this, unfortunately.
