### ISSUE TITLE
Extybn doesn't show opcode 

### ISSUE THREAD

**Issue by Sisulizer** [regomne/chinesize#39]
Wonder if I did anything wrong. 
https://user-images.githubusercontent.com/91543117/143775455-94c2f7fb-0562-4d99-8101-e0f2b0ce29b6.mp4

**Comment by regomne** [comment]
Please upload the ybn files and I will have a try.

**Comment by Sisulizer** [comment]
here
[ysbin.zip](https://github.com/regomne/chinesize/files/7624950/ysbin.zip)

**Comment by regomne** [comment]
These ybn files have already been decrypted. You may use

```bash
extYbn -e -output-opcode -ybn yst00259.ybn -key 0
```

 to get the opcode.
(I choose yst00259 as it seems big enough to guess the opcode, and "-key 0" means "do not try to decrypt with the default key".)

Then use

```bash
extYbn.exe -e -op-msg 108 -op-call 43 -ybn yst00259.ybn -key 0 -txt yst00259.txt
```

to extract the text.
