### ISSUE TITLE
extYbn不能解包yuris 555版本的ybn文件

### ISSUE THREAD

**Issue by 124asd** [regomne/chinesize#40]
大大您好，请问extYbn是不是不能解包yuris 555版本的ybn文件？我已经提取到密钥了，用extYbn 执行该命令：extYbn -e -ybn yst00274.ybn -txt yst00274.txt -key 0xEF16F974 来提取文本会报内存溢出的错误，如果用别的软件是可以解包出文本，但是导出来的是日文编码，最后导入只能用日文编码，这样会有一些中文词完全没法写入，因而希望能用extYbn来解决这个问题。

**Comment by regomne** [comment]
发一下全部ybn文件我测一下

**Comment by 124asd** [comment]
> 发一下全部ybn文件我测一下

好的 这是解包出来的ysbin文件：
[ysbin.zip](https://github.com/regomne/chinesize/files/9259266/ysbin.zip)

**Comment by regomne** [comment]
key是 0x74f916ef，key是没错，不过有大小端的区别，如果不了解的话下次可以尝试像这样两个一组的颠倒一下位置。

这样guess一下opcode

```
extybn -e -ybn yst00344.ybn -key 0x74f916ef -output-opcode
msg     call
108     43
```

然后这样解包

```
extybn -e -ybn yst00344.ybn -key 0x74f916ef -op-msg 108 -op-call 43 -txt yst00344.txt
```

**Comment by 124asd** [comment]
> st00344.ybn -key 0x74f916ef -op-msg 108 -op-call 4

非常感谢 不打扰你了
