### ISSUE TITLE
用extYbn进行Guess opcodes时出现报错

### ISSUE THREAD

**Issue by AI-lumin** [regomne/chinesize#41]
没有在release里找到extYbn.exe，于是自己编译了一个，使用的时候出现问题
通过观察得知密钥为`0x263b0130`

以下是我的报错，如果密钥不对，会出现内存不足的情况
`D:\(workplace\yuris\extYbn>extYbn -e -ybn yst00007.ybn -output-opcode -key 0x30013b26
runtime: VirtualAlloc of 372916224 bytes failed with errno=1455
fatal error: out of memory`

后来注意到大小端，再试了一下无法猜出opcodes，不知道是为什么
`D:\(workplace\yuris\extYbn>extYbn -e -ybn yst00007.ybn -output-opcode -key 0x263b0130
Guess opcodes failed, msg op:0x0, call op:0x0`

以下是ysbin附件，请大佬指教
[ysbin.zip](https://github.com/regomne/chinesize/files/9276649/ysbin.zip)

**Comment by regomne** [comment]
大概看了下应该是密钥不对。密钥不对的话不一定会内存溢出
