### ISSUE TITLE
NeXAs文本提取不出来

### ISSUE THREAD

**Issue by kangmeiyuanchao** [regomne/chinesize#43]
我用extTxtFromBin.py提取[221223] [戯画] ガールズフランティッククラン 豪華版的文本，但是txt文件里是空的，用编辑器看是解包成功了
![bug问题](https://user-images.githubusercontent.com/89840896/211729999-0bb7a5e5-ac3a-4827-b4d9-6943d4a08ccf.png)

**Comment by kangmeiyuanchao** [comment]
还有在提取[戯画]アイキス3的文本的时候会出现
fs.write(b'\r\n'.join(lines).decode('932').encode('U16'))
UnicodeDecodeError: 'cp932' codec can't decode byte 0x9d in position 1580: illegal multibyte sequence
这个BUG

**Comment by kangmeiyuanchao** [comment]
![bug问题](https://user-images.githubusercontent.com/89840896/212039444-8453ee60-b735-4190-80b0-2597c59abca1.png)
报错的是fs.write(b'\b\n'.join(lines).decode('932').encode('U16'))，我是不是要改b'\b\n'

**Comment by regomne** [comment]
我是说把要解包的文件打包发出来看下。
那个报错是因为格式不兼容。

**Comment by kangmeiyuanchao** [comment]
[Script.txt](https://github.com/regomne/chinesize/files/10409559/Script.txt)
后缀改为7z

**Comment by kangmeiyuanchao** [comment]
麻烦大佬了

**Comment by lleuad-Codi** [comment]
> 麻烦大佬了

[Dump.7z.txt](https://github.com/regomne/chinesize/files/10466153/Dump.7z.txt)

可以正常提取，参考方案：
https://github.com/Inori/FuckGalEngine/blob/master/GIGA/giga_text_out.py
实际上，直接以SJIS编码查看文件，可以看到剧本

**Comment by lleuad-Codi** [comment]
> [Script.txt](https://github.com/regomne/chinesize/files/10409559/Script.txt) 后缀改为7z

[Dump.7z.txt](https://github.com/regomne/chinesize/files/10467030/Dump.7z.txt)
可以正常提取，参考方案：
https://github.com/Inori/FuckGalEngine/blob/master/GIGA/giga_text_out.py

**Comment by kangmeiyuanchao** [comment]
好的谢谢
