### ISSUE TITLE
Question about Exhibit

### ISSUE THREAD

**Issue by Cosetto** [regomne/chinesize#48]
Your extrld.py is the best code I can found for Exhibit on github right now, so I wonder if there will be an update for insert function since Ineditor is out of update? I can manage with the encryption, so what really bother me is how to insert the text back.

**Comment by regomne** [comment]
lneditor is not maintained, but it should still work with rld files. Batch export/import may work.

**Comment by regomne** [comment]
Then it's essential to create a script for packing based on extrld.py. I'll work on it if I have time, but my schedule is quite tight these days. If you're proficient in reading and writing Python code, you might want to give it a try on your own.

**Comment by Cosetto** [comment]
Guess I'll wait for you, I'm not good with these things

**Comment by Cosetto** [comment]
I forgot to tell you that the game was Imouto Paradise 3

**Comment by regomne** [comment]
I have added support for packing rld with new python script. You may have a try.

**Comment by Cosetto** [comment]
Thank you so much. It works like charm

**Comment by Cosetto** [comment]
Hello there, sorry for bothering you again, but there's an issue appeared with the code.
I'm translating an English game and I have to add `txt.append('\t'+s.decode(cp, errors='ignore'))`, else the game will throw error. And as the result, the code skipped those error lines. Is there anyway to remain them?
![image](https://github.com/regomne/chinesize/assets/81801486/1c7ced47-3f94-4921-804c-1f7bcdc00238)
[exhibit.zip](https://github.com/regomne/chinesize/files/12265986/exhibit.zip)

**Comment by Cosetto** [comment]
Okay, so if I change to <4 in these lines:
```
      for s in strs:
        if s != b'*' and s != b'$noname$' and len(s) != 0 and s.count(b',') < 4:
          pure_txt.append(s.decode(cp))
    elif op == 21:
      for s in strs:
        if s != b'*' and s != b'$noname$' and len(s) != 0 and s.count(b',') < 4:
```
It should extract those, but I'm not sure what this is though.

**Comment by Cosetto** [comment]
![image](https://github.com/regomne/chinesize/assets/81801486/883847da-2ab4-4710-a83f-8da873abbee4)
No wait, I just skimmed through and there're still some lines missing, should I just make it < 20?

**Comment by regomne** [comment]
1 The reason for the error is that there are some problems with the contents of the defChara.rld file.
2 The text extraction logic in this script assumes that the text is Japanese or Chinese. If you want to extract English, you may need to deal with the comma count logic and the is_half function.

**Comment by Cosetto** [comment]
Thanks, I'm not sure if this will break the engine or not but when I turn it into "< 30", all text are extracted. So I guess this will do it. Sorry for bothering you again.
