### ISSUE TITLE
import strfile

### ISSUE THREAD

**Issue by yqw1231** [regomne/chinesize#49]
Hello, may I ask if the strfile package in some py files was written by myself? I did not find strfile.py in all files, may I ask if it was lost?

**Comment by regomne** [comment]
Yeah, it's too old and I lost it. 😂

**Comment by yqw1231** [comment]
> Yeah, it's too old and I lost it. 😂
ok, is there any difference between bytefile and strfile? I want to try to imitate it.

**Comment by regomne** [comment]
strfile is used in py2.X, function of which is similar with bytefile in py 3.X.

**Comment by yqw1231** [comment]
so the the function strfile.MyStr is same as the __init__ in bytefile?

**Comment by regomne** [comment]
I remeber so.

**Comment by yqw1231** [comment]
def MyStr(Src):
    return bytefile.ByteFile(Src)
Thanks, I'm trying to write this now, but I'm getting some errors, I think it's because some functions in python2 are not compatible with python3. Am I on the right track?

**Comment by yqw1231** [comment]
I use the bytefile3.2.py, but an error has occurred.I think maybe there's something wrong with my thinking.
self.b=bytearray(Src)
           ^^^^^^^^^^^^^^
TypeError: string argument without an encoding

**Comment by regomne** [comment]
Should always use str instead of bytearray in python2.

**Comment by yqw1231** [comment]
In python2? Since my configuration environment is python3, do I now need to change the str in extsee.py to bytearray?

**Comment by regomne** [comment]
You should modify codes about bytes processing in extseen.py if you run it in python3.
Additionally, extseen.py only works with some old games using Reallive engine.

**Comment by yqw1231** [comment]
Just now I ran Extseen in python2.7, but I still got an error. After I modified the ord() problem, I found that the sentence "return".join(uncompr) "got an error, so I should use str instead of bytearray as you said. Change the code in bytefile2.7.py?

**Comment by yqw1231** [comment]
So in the end, I made two modifications, one is to delete bytearray from bytefile, and the other is to change tData[3] to ord(tData[3]) in readu32 function. Finally, it ran successfully and extracted some txt files. But most of the files are garbled, although I changed to shift-jis encoding, and there are some Japanese, but there are still a lot of garbled codes, so I think whether the game is new, or I modified the wrong.

**Comment by yqw1231** [comment]
[py files.zip](https://github.com/regomne/chinesize/files/11954960/py.files.zip)
This is my code

**Comment by yqw1231** [comment]
![U`0YOS1HRPHW60`~}W}CNPL](https://github.com/regomne/chinesize/assets/136776881/99827c4d-da0d-4249-a2cd-3d6064e15346)
This is the photo of a file.

**Comment by regomne** [comment]
It seems that extseen successfully decrypt the seen file, but the DECRYPTED file is still a BINARY file, not a pure-text file. You may find other tools to extract and pack it.

**Comment by yqw1231** [comment]
Thanks
