### ISSUE TITLE
KrKr2 PSB

### ISSUE THREAD

**Issue by marcussacana** [regomne/chinesize#5]
hello, is the same boring ever
i try use your PSB extractor of KrKr2... and works... but
![fail](https://cloud.githubusercontent.com/assets/10576957/6549464/558c9544-c5f2-11e4-9a2b-f53f65d72a0c.png)
----
this psbparse was to reinsert translation in dec.txt to the psb? if not, you know name of one tool for that?
I really need (again tehe~)a way to do this....

**Comment by regomne** [comment]
yes there is a tool which can directly extract the text of psb... but its UI is in Chinese

**Comment by marcussacana** [comment]
serious ?, glad I hear that. if you can get me the link or at a minimum the name of this tool I would be grateful. sorry for the inconvenience ...

**Comment by regomne** [comment]
https://github.com/regomne/lneditor/releases/tag/v2.1.2 
to open: 文件--打开原始脚本
to export a script to a txt: 文件--导出为txt
to export scripts by folder: 批量--批量导出txt
to import txts by folder: 批量--批量导入

**Comment by marcussacana** [comment]
thanks man

**Comment by marcussacana** [comment]
the download allways fail.... i try with my vpn server and fail again kkkk
the source folder have the bin... i can use this? or i need find uploaded in other site to download?

**Comment by marcussacana** [comment]
ohh sorry, i use a download manager and fail the download this that... i download using my browser and work thanks man

**Comment by marcussacana** [comment]
this tool... is the BEST kkkkkkk
THANKSSS, i love you kkkkkkkkkkkkkkkk
THANKSSSSS
