### ISSUE TITLE
extYbn进行Guess opcodes时报错

### ISSUE THREAD

**Issue by bluedomain** [regomne/chinesize#51]
感谢大佬的工具。
github里没有exe文件，所以我自己编译了一个。
通过Dir-A的教程找到了密钥0x96AC6FD3，同时Dir-A的密钥自动寻找工具也给了这个密钥。
在寻找opecodes时报错，调换大小端顺序没有效果。尝试了后二十个和前两个ybn文件也不行。

以下是我的命令和报错信息。
能帮忙看一下吗，谢谢！

**命令：**
./extybn -e -ybn yst00283.ybn -key 0x9bac6fd3 -output-opcode

**错误信息：**
runtime: VirtualAlloc of 1816657920 bytes failed with errno=1455
fatal error: out of memory

runtime stack:
runtime.throw({0xe1f3a8?, 0xd08b5ec000?})
        A:/Programs/Go/src/runtime/panic.go:1077 +0x65 fp=0xbdc69ff528 sp=0xbdc69ff4f8 pc=0xd63d05
runtime.sysUsedOS(0xd07f282000, 0x6c480000)
        A:/Programs/Go/src/runtime/mem_windows.go:83 +0x1bb fp=0xbdc69ff588 sp=0xbdc69ff528 pc=0xd4579b
runtime.sysUsed(...)
        A:/Programs/Go/src/runtime/mem.go:77
runtime.(*mheap).allocSpan(0xf2c520, 0x36240, 0x0, 0x60?)
        A:/Programs/Go/src/runtime/mheap.go:1351 +0x487 fp=0xbdc69ff628 sp=0xbdc69ff588 pc=0xd55547
runtime.(*mheap).alloc.func1()
        A:/Programs/Go/src/runtime/mheap.go:968 +0x5c fp=0xbdc69ff670 sp=0xbdc69ff628 pc=0xd54cfc
traceback: unexpected SPWRITE function runtime.systemstack
runtime.systemstack()
        A:/Programs/Go/src/runtime/asm_amd64.s:509 +0x49 fp=0xbdc69ff680 sp=0xbdc69ff670 pc=0xd8cbc9

[ysbin.zip](https://github.com/regomne/chinesize/files/13557933/ysbin.zip)

**Comment by regomne** [comment]
加密方式比较特殊，这些文件是原始的、从游戏的资源封包文件中解出来的吗？

**Comment by bluedomain** [comment]
应该是的，用Crass Crage 解包出来的，使用Crage GUI 无额外指令。
 我用的crass是从这个地址下的 ( https://github.com/rinrin-/crass/tree/master）
最开始想用GARbro，但是解包不了。

**Comment by regomne** [comment]
试下换个工具看能不能解出来？这个加密方式看起来挺奇怪的…感觉不太像原本的加密方式

**Comment by bluedomain** [comment]
使用其他工具解包出来的ybn文件也报错

arc_conv解出来的是乱码

Yuris text replacer和Crass 0.4.14解出来的文件都是一样大小和名字，应该是正常解出来了。

尝试用其他人后来编写的新Crass YU-RIS解包插件，并使用解包出来的ybn文件也报错 （ https://www.cnblogs.com/sunjicccc/archive/2013/01/02/2841956.html ）

GARbro mod因为程序无法自动判断加密方式所以解不出来，即便尝试多个同引擎其他游戏的加密方式也是解不出来（ https://github.com/crskycode/GARbro/releases/tag/GARbro-Mod-1.0.1.2 )

参考：
https://forums.fuwanovel.net/topic/24704-a-complete-guide-to-unpack-and-repack-yu-ris-engine-files/

**Comment by regomne** [comment]
只要能解出来，都发出来看下

**Comment by bluedomain** [comment]
[ysbin-yu-ris text replacer.zip](https://github.com/regomne/chinesize/files/13573817/ysbin-yu-ris.text.replacer.zip)
[ysbin-新Crass插件.zip](https://github.com/regomne/chinesize/files/13573819/ysbin-.Crass.zip)
[ysbin-GARbro.zip](https://github.com/regomne/chinesize/files/13573820/ysbin-GARbro.zip)
[ysbin-原始Crass0.4.14.zip](https://github.com/regomne/chinesize/files/13573845/ysbin-.Crass0.4.14.zip)

arc_conv解出来的是乱码加大量有乱码名字的空文件夹，完全不能使用，所以没上传

**Comment by regomne** [comment]
好，晚些时候我对比看看

**Comment by regomne** [comment]
不好意思上个月后来忘了这事了。
新crass插件和Garbro的里面的是解密过后的，用-key 0可以正常猜测opcode。
text replacer里面的是未解密的，用默认key 0x96AC6FD3也可以猜测。（**你贴的命令里面的key写的是错的**）
0.4.14的解包文件是有问题的。

```
d:\temp\yuris\ysbin-.Crass\ysbin>extybn -e -ybn yst00283.ybn -key 0 -output-opcode
msg     call
90      29
```
