### ISSUE TITLE
Catsystem2汉化后动态失效的问题

### ISSUE THREAD

**Issue by rehomeSatan-debug** [regomne/chinesize#52]
导出Catsystem2的cst文件并汉化后，以gbk或者utf-8格式封包回去，游戏可以正常运行，但是会出现动态立绘失效的问题，我找了所有的kcs文件和fes文件，遗憾的是都没有找到可以解决这个问题的内容。
请问作者了解怎么解决这个问题吗？

**Comment by rehomeSatan-debug** [comment]
全部文件梳理了一下，立绘的动作控制文件应该是在m2config.int里面，里面的.inc文件和.pfl文件打开后可以看到是932编码，在把编码全部修改成936编码之后，即使用游戏的原始文件打开游戏，所有的动态立绘动作也都会失效。
但是此时用936编码打开游戏，依旧无法正常出现动态立绘的动作，也就是还有需要改的点。

**Comment by regomne** [comment]
立绘的显示通常来说是通过脚本中的文本在某个文本到图片的映射集中查找出来的。这里的“文本”指的是原始编码的字节，所以对于汉字/假名来说932和936编码是不一样的。你要测试的话就得一点点的修改和测试来找出到底改了哪里会导致立绘不显示。比如只对cst文本的部分内容进行转码以测试。

**Comment by rehomeSatan-debug** [comment]
我测试了这个动态立绘和文本应该没有关系。
测试顺序是：
① 932编码的启动器打开游戏日文文本，动态立绘正常
② utf-8编码的启动器打开游戏中文文本，动态立绘失效
③ 932编码的启动器打开游戏中文文本，动态立绘正常
④ utf-8编码的启动器打开游戏日文文本，动态立绘失效
因此可以确定的是，动态立绘的启用和文本类型无关，只和启动器的编码方式有关。

尝试删除m2config.int，但是保留游戏立绘文件，结果，游戏中立绘消失，可以确定的m2config.int中的文件控制立绘。

因此尝试m2config.int内的文件编码修改
把m2config.int内的文件保持932格式不动：
1、utf-8的启动器打开游戏，动态立绘失效。
2、932的启动器打开游戏，动态立绘正常。

把m2config.int内的文件修改为utf-8格式：
1、utf-8的启动器打开游戏，动态立绘失效。
2、932的启动器打开游戏，动态立绘正常。

依旧没有解决动态立绘失效的问题。非常费解，用来做测试的游戏的甜蜜女友2+。

奇怪的是我在前作甜蜜女友2中测试的结果是修改m2config.int中，可以保证动态立绘在utf-8编码的中文文本下正常工作，现在百思不得其解，希望作者可以提供一点思路，感激不尽。

**Comment by regomne** [comment]
启动器是什么？

rehomeSatan-debug ***@***.***>于2024年3月9日 周六22:16写道：

**Comment by rehomeSatan-debug** [comment]
就是游戏的exe文件

**Comment by regomne** [comment]
你说的不同编码的启动器，是通过什么方式调整编码的？

**Comment by rehomeSatan-debug** [comment]
x64debug，修改MultiByteToWideChar前面的push 3A4为push FDE9

**Comment by regomne** [comment]
那应该还是某处显示文本之外的文本使用的编码的问题，建议首先改成936编码做测试，因为引擎对utf8的支持不一定那么完善；其次找找其他的可能存在文本的文件，你删掉m2config导致立绘消失可以证明它对显示立绘是必要的，但是不能证明是充分的，也就是说还有可能存在其他文件影响立绘显示；最后需要确保你所进行的文件转码是完整的，没有漏掉某些字符串。

**Comment by rehomeSatan-debug** [comment]
936是我最早用的编码，不行，因为在m2config中的文本里有936不支持的符号，最后也无法正常显示动态立绘。
我也想过有除了m2config之外的文件，但是没有找到。

**Comment by regomne** [comment]
936无法显示的字符可以尝试用其他字符替代，建议先用936尝试。如果实在找不到其他的文件的话可以把游戏名字发出来我有空了看看，不过可能要以月为单位等一等

**Comment by rehomeSatan-debug** [comment]
没事，我现在基本已经搞懂了逻辑，立绘的具体文件在psz.int里，动作控制文件在m2config,int里面，理论上改了m2config就可以了，但是却没有成功。
游戏名字是甜蜜女友2+
我在同样使用了动态立绘的该社前作甜蜜女友2 Perfect Edition中通过修改m2config成功使动态立绘出现了，但是在甜蜜女友2+这个fd上却失败了，比较奇怪。
感觉作者的耐心解答，我再自己好好研究一下。
