### ISSUE TITLE
 ExHIBIT 引擎游戏密钥寻找 在调试器搜哪个断点？ 游戏是星空Teaparty

### ISSUE THREAD

**Issue by ZEdwdsad** [regomne/chinesize#53]

**Comment by ZEdwdsad** [comment]
我看它是有两个秘钥的 求问大佬

**Comment by regomne** [comment]
两个密钥，一个是用于解密def.rld文件的，另一个是用于解密其余所有rld文件的。
寻找方法就是在CreateFile & ReadFile上下断点，然后跟踪一下对读到的buff处理过程就行了。
