### ISSUE TITLE
关于rugp解包问题

### ISSUE THREAD

**Issue by ghost** [regomne/chinesize#54]
大佬好，我最近正在筹备汉化マブラヴ ALTERED FABLE，期间遇到了程序问题。rUGP版本是5.8。
我已经对代码进行修改，但是解包到后期会对应不到VM指令然后结束。想问下这种该如何下手解决（ReadClass也看了，但是不好改，然后那里就没有对应的指令）。
谢谢。

**Comment by regomne** [comment]
这个引擎的资源包格式比较复杂，遇到这类问题只能靠调试、跟踪游戏来解决

**Comment by Rarted4** [comment]
There is a english translation project for the same game, maybe they can help https://forums.fuwanovel.net/topic/29569-muv-luv-altared-fable-translation-patch-play-testers-needed/
