### ISSUE TITLE
Where is strfile

### ISSUE THREAD

**Issue by Neroldy** [regomne/chinesize#8]
菊苣我想问一下在reallive里面那个extseen.py中的import strfile，这个貌似是自己写的库？可是我好像并没有找到这个文件。想问一下这个文件的具体实现，谢谢！

**Comment by regomne** [comment]
这个比较老了，自己阅读一下代码理解吧，因为就算脚本能运行起来，也难以对新游戏生效的。

**Comment by Neroldy** [comment]
好的，谢谢菊苣。
