### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by 0xh3LL0** [regomne/chinesize#9]
Hello, i have some issue when i want to build your catsystem2 tools
<a href="https://imgur.com/O7bfAKY"><img src="https://i.imgur.com/O7bfAKY.png" title="source: imgur.com" /></a>

i run on win xp sp3, go 1.9.2 with internet connection
here is what i already tried:
download bstream and eutil,
extract them to working directory, didnt work
extract them to go path (go\bin\src) directory, didnt work
extract them to go root (go\bin) directory, didnt work
if i put them in the wrong place, where should i put them?
and since i think that the code may need some dependencies, i turn on my internet, but still no luck...

**Comment by regomne** [comment]
You need to set GOROOT nad GOPATH environment variable, and then run
go get github.com/regomne/eutils/XXXXX
For more information, read https://golang.org/doc/install

**Comment by 0xh3LL0** [comment]
okay, so i install go on win 10, set goroot and gopath
clone the git (which require me to install git)
and finally i can build them, but only cst.go and ext.go
there is an error when i try to build pack.go
<a href="https://imgur.com/nUcTPHz"><img src="https://i.imgur.com/nUcTPHz.png" title="source: imgur.com" /></a>

**Comment by regomne** [comment]
In golang, a folder is a project, and _go build_ will build all the .go files in the folder.
Try to keep the original directory and files, and then run _go build_ in each project directory.

**Comment by regomne** [comment]
Oh, some codes are not yet pushed to github, pull it tomorrow, please.

**Comment by 0xh3LL0** [comment]
so that how it was, i'll wait tomorrow.

**Comment by 0xh3LL0** [comment]
anyway, i put only pack.go in one folder without something else...

**Comment by 0xh3LL0** [comment]
hello?
